public/404.html
public/index.html

History fallback support

---

package-lock.json
package.json
src/components/NewProject/NewProject.css
src/components/NewProject/index.js
src/components/ProjectInput/index.js
src/components/ProjectsList/ProjectItem.js
src/components/ThymeTable/Entry.js

Remove react-select

---

src/actions/projects.js
src/components/NewProject/index.js
src/components/ProjectInput/index.js
src/components/ThymeTable/Entry.js
src/components/ThymeTable/New.js
src/components/ThymeTable/index.js

Add project from timesheet page

---

src/core/thyme.js

Put date range to start and end of day on reports

---

flow-typed/thymeLibDef.js
src/components/ThymeTable/Entry.js
src/components/ThymeTable/New.js
src/core/localStorage.js

Will prevent the timer from stopping on navigation. You can even close the whole tab!
Closes #21

Continue timer on navigate

---

flow-typed/thymeLibDef.js
package-lock.json
src/components/App/index.js
src/components/App/print.css
src/components/ReportCharts/index.js
src/components/ReportDetailed/index.js
src/components/ReportFilters/index.js
src/components/ReportTable/index.js
src/components/SavedReports/SavedReports.css
src/components/ThymeTable/Entry.js
src/core/thyme.js
src/pages/Reports.js

Adds detailed report with time entries to reports page

Detailed reports

---

package-lock.json
package.json
src/components/ReportRange/index.js

#38 Added the week to date button, if wanted.

Added the week to date button on the reports page

---

package-lock.json
package.json
src/actions/app.js
src/components/App/App.css
src/components/App/index.js
src/components/ProjectsList/ProjectItem.js
src/components/SavedReports/index.js
src/components/ThymeTable/Entry.js
src/index.js
src/pages/Settings.js
src/reducers/app/index.js
src/reducers/index.js

Confirms and alerts

---

package-lock.json
package.json
src/components/ReportTable/index.js
src/core/thyme.js

Fix date formatting

---

src/pages/Settings.js

Add dispatched alert to props

---

flow-typed/thymeLibDef.js
src/__tests__/migrations.spec.js
src/__tests__/thyme.spec.js
src/actions/app.js
src/components/ReportDetailed/index.js
src/components/ThymeTable/Entry.js
src/core/importExport.js
src/core/localStorage.js
src/core/thyme.js
src/index.js
src/middleware/migrate.js
src/migrations/index.js
src/pages/Reports.js
src/pages/Settings.js
src/pages/Time.js
src/reducers/index.js
src/reducers/time/time.js

Migrate time entry date and times to timestamps

---

src/core/thyme.js

Round minutes in duration to prevent rounding errors

---

src/core/thyme.js
src/pages/Reports.js
src/pages/Time.js

Fix sorting

---

src/__tests__/thyme.spec.js
src/components/ReportTable/index.js
src/components/ThymeTable/Entry.css
src/components/ThymeTable/Entry.js
src/core/thyme.js

Seconds in timer

---

package-lock.json
package.json

Pre Push Git hooks

---

src/components/Settings/ImportExport.js

Pass data to import instead of function

---

flow-typed/thymeLibDef.js
package-lock.json
package.json
src/__tests__/integration/time.spec.js
src/actions/time.js
src/components/DateRange/index.js
src/components/DateSort/DateSort.css
src/components/DateSort/index.js
src/components/ThymeTable/index.js
src/core/thyme.js
src/pages/Reports.js
src/pages/Time.css
src/pages/Time.js
src/reducers/time/index.js
src/selectors/time.js

Sorting timetable

---

.eslintrc.js
src/__tests__/integration/projects.spec.js
src/components/App/App.css
src/components/App/index.js
src/components/DateRange/index.js
src/components/NewProject/index.js
src/components/ProjectsList/ProjectItem.js
src/components/ProjectsList/ProjectsList.css
src/components/ProjectsList/index.js
src/components/Settings/Account.js
src/components/Settings/DeleteData.js
src/components/Settings/ImportExport.js
src/components/ThymeTable/Entry.css
src/components/ThymeTable/Entry.js
src/components/ThymeTable/index.js
src/pages/Settings.css
src/pages/Settings.js
src/pages/Time.css
src/pages/Time.js

Mobile layouts

---

src/core/reportQueryString.js

Fixes querystring parsing for reports page

---

src/components/ReportFilters/ReportFilters.css
src/components/SavedReports/SavedReports.css
src/pages/Reports.js

small updates for mobile layout reports page (making the grid stackable and reorder on mobile)

update mobile layout reports page

---

src/components/ReportDetailed/ReportDetailed.css
src/components/ReportRange/ReportRange.css

Fix print CSS for detailed reports

---

.travis.yml
package-lock.json
package.json

Fix linting CI

---

src/components/ReportDetailed/index.js
src/core/reportQueryString.js

Fix the "no project" toggle

---

src/components/App/App.css
src/components/App/index.js
src/components/App/print.css
src/sections/Reports/components/ActionMenu/index.js
src/sections/Reports/index.js

Action bar post merge clean up

---

.travis.yml
package.json

Something to think about but it means that will be a yarn dependency. 
closes #140.

Edited the travis file and added the yarn.lock file

---

src/sections/TimeSheet/components/Entry/Entry.js
src/sections/TimeSheet/index.js

Ability to clear temporary item

---

src/__tests__/unit/breakpoints.spec.js
src/components/App/index.js
src/components/Responsive/index.js
src/sections/Projects/components/NewProject/index.js
src/sections/Projects/components/ProjectsList/ProjectItem.js
src/sections/Projects/components/ProjectsList/index.js
src/sections/TimeSheet/components/Entry/Entry.js
src/sections/TimeSheet/components/Table/index.js
src/sections/TimeSheet/index.js

Refactor responsive component for render prop approach

---

src/components/App/index.js
src/sections/Account/index.js

Do not render menu items twice within breakpoints

---

flow-typed/thymeLibDef.js
src/components/App/index.js
src/epics/index.js
src/plugins/ProjectRates/index.js
src/plugins/ProjectRates/injectables.js
src/plugins/ProjectRates/reducers.js
src/reducers/app.js
src/reducers/index.js
src/register/component.js
src/register/epic.js
src/register/plugin.js
src/register/reducer.js
src/register/settings.js
src/sections/Account/reducers.js
src/sections/Projects/components/ProjectsList/ProjectItem.js
src/sections/Projects/components/ProjectsList/index.js
src/sections/Projects/reducers/index.js
src/sections/Projects/reducers/project.js
src/sections/Reports/components/Table/index.js
src/sections/Reports/reducers/index.js
src/sections/Reports/reducers/report.js
src/sections/Settings/Settings.js
src/sections/Settings/reducers/index.js
src/sections/Settings/reducers/rounding.js
src/sections/Settings/reducers/timesheet.js
src/sections/TimeSheet/TimeSheet.js
src/sections/TimeSheet/reducers/index.js
src/sections/TimeSheet/reducers/time.js

Separate register modules

---

src/plugins/ProjectRates/async.js
src/register/table.js
src/sections/Reports/Reports.js
src/sections/Reports/components/Detailed/ReportDetailed.css
src/sections/Reports/components/Detailed/index.js

Refactor detailed view

---

public/index.html

Allow adding external scripts to the output HTML

---

src/sections/TimeSheet/components/Entry/Entry.js

Check if temporary timer is more than a day ago

---

package-lock.json
package.json
src/register/component.js
src/register/epic.js
src/register/reducer.js
src/register/settings.js
src/register/table.js

Allows registering external function in Thyme
Fixes #167

Use `thyme-connect`

---

.gitignore
README.md
package.json
scripts/create-mock.js

Generate mock data

---

src/sections/Reports/components/Detailed/index.js

Change detailed view checkbox to onChange

---

package.json
src/sections/Account/actions.js
src/sections/Account/epics.js
src/sections/Account/reducers.js
src/sections/Projects/components/ProjectsList/ProjectsList.css
src/sections/Projects/components/ProjectsList/index.js
src/sections/Reports/Reports.js
src/sections/Reports/components/Charts/ReportCharts.css
src/sections/Reports/components/Charts/index.js
src/sections/Reports/components/Detailed/index.js
src/sections/Reports/index.js

Empty states

---

package.json

As part of #215, copy current package.json to build folder

Add package copy and bump version

---

package.json
src/sections/Projects/components/ProjectInput/index.js
src/sections/TimeSheet/components/DateInput/index.js
src/sections/TimeSheet/components/Entry/Entry.js
src/sections/TimeSheet/components/NotesInput/index.js
src/sections/TimeSheet/components/TimeInput/index.js

Improve mobile UX

---

package.json
src/__tests__/integration/time.spec.js
src/__tests__/unit/projects.spec.js
src/core/projects.js

Sort projects by name and hierarchy

---

package.json
src/serviceWorker.js

Send a "skipWaiting" message to the service worker when update is available

Skipwaiting SW

---

package.json
src/serviceWorker.js

To work around #244 for the moment

Disable service worker firefox

---

.eslintrc.js
package-lock.json
package.json
src/components/App/index.js
src/components/ChangeOnBlurInput/index.js
src/components/ErrorBoundary/index.js
src/components/Responsive/index.js
src/index.js
src/sections/Projects/Projects.js
src/sections/Projects/components/NewProject/NewProject.css
src/sections/Projects/components/NewProject/index.js
src/sections/Projects/components/ProjectInput/index.js
src/sections/Projects/components/ProjectsList/ProjectItem.js
src/sections/Projects/components/ProjectsList/ProjectsList.js
src/sections/Projects/components/ProjectsList/index.js
src/sections/TimeSheet/TimeSheet.js
src/sections/TimeSheet/components/Table/index.js

Ability to use Responsive as a hook

---

package.json
src/plugins/Insights/components/Insights/index.js
src/sections/Reports/Reports.js
src/sections/Reports/components/Charts/index.js

Reports fixes

---

package.json
src/components/App/index.js
src/components/BuySubscription/Complete.js
src/components/Notifier/index.js
src/core/useRedux.js
src/plugins/ProjectRates/components/Projects/ProjectHourlyRate.js
src/plugins/ProjectRates/components/Reports/ReportTableRow.js
src/plugins/ProjectRates/components/Reports/ReportTableTotal.js
src/plugins/ProjectRates/components/Settings/ProjectRatesSettings.js
src/plugins/ProjectRates/injectables.js
src/register/Consumer.js
src/register/Context.js
src/register/component.js
src/sections/Account/components/ListSubscription.js
src/sections/Account/components/Login.js
src/sections/Account/screens/Premium/index.js
src/sections/Account/screens/Settings/Subscription.js
src/sections/Projects/Projects.js
src/sections/Projects/components/NewProject/index.js
src/sections/Projects/components/ProjectInput/index.js
src/sections/Projects/components/ProjectsList/ProjectsList.js
src/sections/Settings/components/Rounding/index.js
src/sections/TimeSheet/TimeSheet.js
src/sections/TimeSheet/actions.js
src/sections/TimeSheet/components/DateRange/index.js
src/sections/TimeSheet/components/Entry/ListEntry.js
src/sections/TimeSheet/components/Table/index.js

First stab at replacing some component's HOC with hooks for Redux
See #258

React Redux hooks

---

package.json
src/__tests__/integration/time.spec.js
src/sections/TimeSheet/TimeSheet.js
src/sections/TimeSheet/components/Entry/ListEntry.js
src/sections/TimeSheet/components/Table/index.js

Lazy edit popup

---

package.json
src/actions/app.js
src/components/App/index.js
src/epics/update.js

Check update interval

---

package.json
src/components/ErrorBoundary/index.js

Chunk loading error

---

flow-typed/thymeLibDef.js
package.json
src/core/extensions/socket.js
src/core/localStorage.js
src/core/sync.js
src/plugins/Insights/index.js
src/plugins/Insights/selectors.js
src/plugins/ProjectRates/index.js
src/plugins/ProjectRates/selectors.js
src/register/plugin.js
src/sections/Account/components/Status/index.js
src/sections/Account/reducers.js
src/sections/Account/selectors.js
src/sections/Projects/selectors.js

I am all for simplicity. And since I think I will not be using a capabilities system any time soon, I have stripped it out.

Remove capabilities checking

---

package.json
src/sections/TimeSheet/components/Table/ListEntry.js

Context menu bug fix

---

package-lock.json
package.json
src/core/intl.js

Fix Intl i-default fallback
